### ISSUE TITLE
vNode build process stops during building " iproute2".

### ISSUE THREAD

**Issue by rva818** [InfraSIM/idic#39]
**[Problem Description]**
I’m trying to depoly InfraSIM on ESXi.
But vNode packages/binarys files cannot be built because the build process stops during building " iproute2".

**[Steps to Reproduce]**
1) git clone https://github.com/InfraSIM/idic.git

2) on  idic directory, run the following command.
`    $ sudo make setupenv`

3) on idic/vcompute/vnode directory, run the following command.
`    $ sudo fakeroot make menuconfig`

**4) comment out below 2 lines in file /idic/vcompute/vnode/.config.**
```
    # CONFIG_REDFISH_SIMULATION is not set
    # CONFIG_PKG_redfishsim is not set
    CONFIG_GIT_REDFISHSIM_URL=""
```
5) modify below last 

1 line in file /home/onon/idic/pdk/content/kconfigs/19-utilities.kconfig.
```
    [before]
    endmenu # Installer menu
    
    [after]
    endmenu
```
6) on idic/vcompute/vnode directory, run the following command.
`    $ sudo fakeroot make`

**[Actual Results]**
Build fails and the following messages were displayed.
[infrasim_log.txt](https://github.com/InfraSIM/idic/files/377517/infrasim_log.txt)

**[Expected Results]**
Build success and idic/pdk/linux/vnode includes “config-3.16.0”, “ramfs.lzma”, “System.map-3.16.0” and “vmlinuz-3.16.0”.

**Comment by fub2** [comment]
Nice issue reporting template, :+1: @rva818 

From log, looks iproute2 build was successful and problem looks like it is redfishsim related. 

https://github.com/InfraSIM/idic/pull/38 PR is trying to remove building redfish. Suppose it should work. @PaynePei submitted this PR and could help this issue as well.

**Comment by emcinfrasim** [comment]
@rva818, could you change the last three lines of .config file as below and have a try
CONFIG_REDFISH_SIMULATION=n
CONFIG_PKG_redfishsim=n
CONFIG_GIT_REDFISHSIM_URL=""

**Comment by fub2** [comment]
#38 PR merged

**Comment by rva818** [comment]
Thanks @fub2, @emcinfrasim,
It works by grace of you.
